// ============================================================
// RFP Analyzer Pro — Historical Engagement Seed Dataset
// Realistic IBM engagement records for similarity matching.
// ~60 % WON / ~40 % LOST across industries and geographies.
// ============================================================

import type { HistoricalEngagement } from '@/types';

/**
 * Seed dataset of 20 past IBM engagements used by the
 * HistoricalEngagementService for similarity ranking, win/loss
 * analysis, and Proposal Confidence Score computation.
 *
 * Each record is immutable at runtime — treat as a read-only constant.
 * `sourceTag: "Bob IBM Research"` marks records that originate from IBM
 * Research / IBM Institute for Business Value findings.
 */
export const HISTORICAL_ENGAGEMENTS: HistoricalEngagement[] = [
  // ── WON ─────────────────────────────────────────────────────
  {
    id: 'eng-001',
    clientName: 'Global Finance Corp',
    projectTitle: 'Core Banking Modernisation on IBM Z',
    industry: 'Financial Services',
    serviceType: 'Application Modernization',
    geography: 'North America',
    deliveryModel: 'Hybrid',
    contractValueUSD: 8_200_000,
    durationWeeks: 52,
    technologies: ['IBM Z', 'COBOL Modernisation', 'Java', 'OpenShift'],
    keywords: ['mainframe', 'banking', 'modernisation', 'cloud migration', 'regulatory compliance'],
    outcome: 'WON',
    winningAttributes: [
      'Deep IBM Z expertise unavailable with competitors',
      'Phased migration de-risked client investment',
      'Dedicated COBOL-to-Java acceleration tooling',
    ],
    lossReasons: [],
    lessonsLearned: 'Phased approach was decisive in final selection over a big-bang rewrite offer.',
    confidenceContrib: 0.88,
    sourceTag: 'Bob IBM Research',
  },
  {
    id: 'eng-002',
    clientName: 'RetailMax Group',
    projectTitle: 'AI-Powered Supply Chain Optimisation',
    industry: 'Retail',
    serviceType: 'Data & AI',
    geography: 'Europe',
    deliveryModel: 'Offshore',
    contractValueUSD: 3_400_000,
    durationWeeks: 36,
    technologies: ['Watson Studio', 'IBM Planning Analytics', 'Python', 'AWS S3'],
    keywords: ['supply chain', 'demand forecasting', 'AI', 'inventory optimisation', 'retail'],
    outcome: 'WON',
    winningAttributes: [
      'Demonstrated 18 % demand-forecast accuracy improvement in POC',
      'IBM Planning Analytics integration with existing ERP',
      'Offshore CIC delivery at competitive price point',
    ],
    lossReasons: [],
    lessonsLearned: 'A fast POC within 4 weeks was the single biggest differentiator.',
    confidenceContrib: 0.82,
    sourceTag: 'Bob IBM Research',
  },
  {
    id: 'eng-003',
    clientName: 'NationalHealth NHS Trust',
    projectTitle: 'Cloud Security & Compliance Programme',
    industry: 'Healthcare',
    serviceType: 'Security Services',
    geography: 'Europe',
    deliveryModel: 'Onshore',
    contractValueUSD: 5_100_000,
    durationWeeks: 48,
    technologies: ['IBM Security QRadar', 'IBM Guardium', 'Azure', 'Zero-Trust Architecture'],
    keywords: ['healthcare', 'security', 'compliance', 'GDPR', 'zero-trust', 'cloud'],
    outcome: 'WON',
    winningAttributes: [
      'Certified NHS-compliant delivery methodology',
      'Integrated QRadar + Guardium reduces alert fatigue',
      'GDPR expertise and DPA contractual protections',
    ],
    lossReasons: [],
    lessonsLearned: 'Regulatory accreditation letters submitted with the bid increased trust score by evaluators.',
    confidenceContrib: 0.79,
  },
  {
    id: 'eng-004',
    clientName: 'LogiTrans International',
    projectTitle: 'Hybrid Cloud Platform Engineering',
    industry: 'Logistics',
    serviceType: 'Cloud & Platform Services',
    geography: 'Asia Pacific',
    deliveryModel: 'Hybrid',
    contractValueUSD: 6_750_000,
    durationWeeks: 40,
    technologies: ['OpenShift', 'IBM Cloud', 'Terraform', 'Ansible', 'Kubernetes'],
    keywords: ['hybrid cloud', 'platform engineering', 'kubernetes', 'logistics', 'devops'],
    outcome: 'WON',
    winningAttributes: [
      'IBM Cloud APAC data sovereignty addressed local regulations',
      'GitOps-first delivery cut release cycle by 70 %',
      'Dedicated SRE team from week one',
    ],
    lossReasons: [],
    lessonsLearned: 'Data residency compliance was the deciding factor over hyperscaler-only bids.',
    confidenceContrib: 0.85,
  },
  {
    id: 'eng-005',
    clientName: 'EnergyGrid PLC',
    projectTitle: 'IoT Asset Management Platform',
    industry: 'Energy & Utilities',
    serviceType: 'Data & AI',
    geography: 'Europe',
    deliveryModel: 'Hybrid',
    contractValueUSD: 4_300_000,
    durationWeeks: 32,
    technologies: ['IBM Maximo', 'Watson IoT', 'Edge Computing', 'Azure IoT Hub'],
    keywords: ['IoT', 'asset management', 'predictive maintenance', 'energy', 'maximo'],
    outcome: 'WON',
    winningAttributes: [
      'Maximo expertise unavailable with other vendors',
      'Predictive maintenance ROI model accepted by CFO',
      'Edge-to-cloud architecture reduced latency by 60 %',
    ],
    lossReasons: [],
    lessonsLearned: 'Pre-built Maximo accelerators halved the implementation timeline vs. custom builds.',
    confidenceContrib: 0.80,
    sourceTag: 'Bob IBM Research',
  },
  {
    id: 'eng-006',
    clientName: 'TelcoStream Inc',
    projectTitle: 'Network Automation & AIOps',
    industry: 'Telecommunications',
    serviceType: 'Managed Services',
    geography: 'North America',
    deliveryModel: 'Offshore',
    contractValueUSD: 9_800_000,
    durationWeeks: 60,
    technologies: ['IBM AIOps', 'Instana', 'OpenShift', 'Python', 'Kafka'],
    keywords: ['AIOps', 'network automation', 'observability', 'telecom', 'kafka', 'managed services'],
    outcome: 'WON',
    winningAttributes: [
      'Instana full-stack observability from day one',
      'AIOps reduced MTTR by 45 % in pilot environment',
      '24/7 NOC from India CIC at manageable cost',
    ],
    lossReasons: [],
    lessonsLearned: 'Demonstrating MTTR improvements via live environment data won the room during orals.',
    confidenceContrib: 0.91,
  },
  {
    id: 'eng-007',
    clientName: 'AutoManufacture AG',
    projectTitle: 'SAP S/4HANA Migration & Integration',
    industry: 'Manufacturing',
    serviceType: 'Application Modernization',
    geography: 'Europe',
    deliveryModel: 'Nearshore',
    contractValueUSD: 12_500_000,
    durationWeeks: 72,
    technologies: ['SAP S/4HANA', 'IBM Sterling', 'MQ', 'Integration Bus'],
    keywords: ['SAP', 'ERP', 'migration', 'manufacturing', 'integration', 'sterling'],
    outcome: 'WON',
    winningAttributes: [
      'IBM Sterling supply-chain integration accelerators',
      'Nearshore delivery with German-speaking leads',
      'Fixed-price milestone model reduced client risk',
    ],
    lossReasons: [],
    lessonsLearned: 'Language and timezone alignment with nearshore team was raised in references.',
    confidenceContrib: 0.77,
  },
  {
    id: 'eng-008',
    clientName: 'BankSecure Ltd',
    projectTitle: 'Fraud Detection ML Platform',
    industry: 'Financial Services',
    serviceType: 'Data & AI',
    geography: 'North America',
    deliveryModel: 'Hybrid',
    contractValueUSD: 2_900_000,
    durationWeeks: 24,
    technologies: ['Watson Studio', 'OpenScale', 'IBM Cloud Pak for Data', 'Spark', 'Python'],
    keywords: ['fraud detection', 'machine learning', 'banking', 'model governance', 'AI fairness'],
    outcome: 'WON',
    winningAttributes: [
      'OpenScale model monitoring satisfied regulatory audit requirements',
      'Explainable AI satisfied risk officer concerns',
      'Out-of-box fraud model library reduced timeline by 8 weeks',
    ],
    lossReasons: [],
    lessonsLearned: 'Model explainability documentation was a formal evaluation criterion — prepare it early.',
    confidenceContrib: 0.86,
    sourceTag: 'Bob IBM Research',
  },
  {
    id: 'eng-009',
    clientName: 'PublicSector Authority',
    projectTitle: 'Digital Citizen Services Portal',
    industry: 'Public Sector',
    serviceType: 'Application Modernization',
    geography: 'North America',
    deliveryModel: 'Onshore',
    contractValueUSD: 7_600_000,
    durationWeeks: 56,
    technologies: ['IBM Carbon Design', 'React', 'Node.js', 'IBM Cloud', 'OpenID Connect'],
    keywords: ['government', 'digital services', 'accessibility', 'citizen portal', 'WCAG', 'identity'],
    outcome: 'WON',
    winningAttributes: [
      'IBM Carbon Design System met WCAG 2.1 AA without customisation',
      'FedRAMP-authorised IBM Cloud deployment',
      'Existing government framework agreements reduced procurement time',
    ],
    lossReasons: [],
    lessonsLearned: 'Framework agreements accelerated contract execution by 3 months — always reference them.',
    confidenceContrib: 0.74,
  },
  {
    id: 'eng-010',
    clientName: 'InsureCore UK',
    projectTitle: 'Claims Automation with Generative AI',
    industry: 'Insurance',
    serviceType: 'Data & AI',
    geography: 'Europe',
    deliveryModel: 'Hybrid',
    contractValueUSD: 4_100_000,
    durationWeeks: 28,
    technologies: ['IBM watsonx.ai', 'Llama-3', 'IBM Cloud Pak for Data', 'REST APIs'],
    keywords: ['generative AI', 'insurance', 'claims automation', 'LLM', 'watsonx'],
    outcome: 'WON',
    winningAttributes: [
      'watsonx.ai on-prem deployment kept data inside EU boundary',
      'Pre-built claims extraction prompt library reduced tuning time',
      'IBM Research partnership on LLM hallucination mitigation cited in bid',
    ],
    lossReasons: [],
    lessonsLearned: 'EU data residency + IBM Research credibility was the decisive combination.',
    confidenceContrib: 0.89,
    sourceTag: 'Bob IBM Research',
  },
  {
    id: 'eng-011',
    clientName: 'MidWest Utility Corp',
    projectTitle: 'Smart Grid Analytics Modernisation',
    industry: 'Energy & Utilities',
    serviceType: 'Data & AI',
    geography: 'North America',
    deliveryModel: 'Hybrid',
    contractValueUSD: 5_500_000,
    durationWeeks: 44,
    technologies: ['IBM SPSS', 'Watson Studio', 'Kafka', 'Hadoop', 'Python'],
    keywords: ['smart grid', 'analytics', 'energy', 'forecasting', 'SPSS', 'streaming'],
    outcome: 'WON',
    winningAttributes: [
      'SPSS migration path preserved client existing models',
      'Streaming analytics on Kafka cut outage detection from 4h to 12 min',
      'Utility-specific compliance library included',
    ],
    lossReasons: [],
    lessonsLearned: 'Protecting existing SPSS investments is a strong message for analytics-mature utilities.',
    confidenceContrib: 0.78,
  },
  {
    id: 'eng-012',
    clientName: 'Asia Pacific Bank',
    projectTitle: 'Open Banking API Platform',
    industry: 'Financial Services',
    serviceType: 'Cloud & Platform Services',
    geography: 'Asia Pacific',
    deliveryModel: 'Offshore',
    contractValueUSD: 3_700_000,
    durationWeeks: 30,
    technologies: ['IBM API Connect', 'OpenShift', 'OAuth 2.0', 'Kong', 'Kubernetes'],
    keywords: ['open banking', 'API platform', 'fintech', 'PSD2', 'oauth', 'APAC'],
    outcome: 'WON',
    winningAttributes: [
      'IBM API Connect pre-certified for MAS TRM compliance',
      'Offshore team had existing APAC banking API accelerators',
      'Rate sandbox delivered in sprint 1 built confidence early',
    ],
    lossReasons: [],
    lessonsLearned: 'Regulatory pre-certification documentation saved 6 weeks of client legal review.',
    confidenceContrib: 0.83,
    sourceTag: 'Bob IBM Research',
  },

  // ── LOST ────────────────────────────────────────────────────
  {
    id: 'eng-013',
    clientName: 'MegaRetail Corporation',
    projectTitle: 'E-Commerce Platform Replatform',
    industry: 'Retail',
    serviceType: 'Cloud & Platform Services',
    geography: 'North America',
    deliveryModel: 'Offshore',
    contractValueUSD: 11_000_000,
    durationWeeks: 64,
    technologies: ['Kubernetes', 'AWS', 'React', 'Microservices', 'GraphQL'],
    keywords: ['e-commerce', 'replatform', 'microservices', 'retail', 'AWS', 'graphql'],
    outcome: 'LOST',
    winningAttributes: [],
    lossReasons: [
      { category: 'Price', reason: 'IBM price was 28 % above winning bid', mitigationForCurrentProposal: 'Benchmark rates against offshore CIC options; present total-cost-of-ownership not day-rate.' },
      { category: 'Speed to Market', reason: 'Client required 8-week launch; IBM proposed 14 weeks', mitigationForCurrentProposal: 'Front-load a delivered MVP scope to hit an early go-live milestone within 8 weeks.' },
    ],
    lessonsLearned: 'Retail clients prioritise speed-to-market over quality assurance frameworks. Lead with velocity.',
    confidenceContrib: 0,
  },
  {
    id: 'eng-014',
    clientName: 'GlobalInsure Group',
    projectTitle: 'Legacy Policy Administration Replacement',
    industry: 'Insurance',
    serviceType: 'Application Modernization',
    geography: 'Europe',
    deliveryModel: 'Hybrid',
    contractValueUSD: 18_000_000,
    durationWeeks: 96,
    technologies: ['Java', 'IBM MQ', 'Oracle DB', 'Angular'],
    keywords: ['insurance', 'policy admin', 'legacy replacement', 'transformation', 'core system'],
    outcome: 'LOST',
    winningAttributes: [],
    lossReasons: [
      { category: 'Vendor Risk', reason: 'Client viewed IBM as strategic but single-vendor risk was cited', mitigationForCurrentProposal: 'Include a named sub-contractor for specialist components to demonstrate ecosystem approach.' },
      { category: 'Domain Expertise', reason: 'Winning vendor had dedicated insurance product accelerator', mitigationForCurrentProposal: 'Lead with IBM Industry Cloud for Insurance and any reference clients in the insurance vertical.' },
      { category: 'Price', reason: 'Total contract value 22 % over budget ceiling', mitigationForCurrentProposal: 'Structure in phases with phase-gate approvals; keep phase 1 within budget ceiling.' },
    ],
    lessonsLearned: 'For large transformation deals, phase-gate structure is essential to stay within client budget cycles.',
    confidenceContrib: 0,
    sourceTag: 'Bob IBM Research',
  },
  {
    id: 'eng-015',
    clientName: 'FastShip Logistics',
    projectTitle: 'Real-Time Tracking Platform',
    industry: 'Logistics',
    serviceType: 'Data & AI',
    geography: 'Asia Pacific',
    deliveryModel: 'Offshore',
    contractValueUSD: 2_100_000,
    durationWeeks: 20,
    technologies: ['Kafka', 'Spark Streaming', 'AWS', 'React Native', 'GPS APIs'],
    keywords: ['real-time', 'tracking', 'logistics', 'streaming', 'mobile', 'kafka', 'GPS'],
    outcome: 'LOST',
    winningAttributes: [],
    lossReasons: [
      { category: 'Technical Fit', reason: 'Client mandated AWS-native; IBM proposed OpenShift on AWS', mitigationForCurrentProposal: 'When client has a cloud mandate, lead with that cloud platform natively rather than abstracting it.' },
      { category: 'Price', reason: 'Day rate differential of 35 % vs. local APAC boutique', mitigationForCurrentProposal: 'Use full offshore CIC pricing model; document IBM quality premium with SLA benchmarks.' },
    ],
    lessonsLearned: 'Respecting client cloud mandates explicitly in the solution avoids technical alignment objections.',
    confidenceContrib: 0,
  },
  {
    id: 'eng-016',
    clientName: 'Continental Pharma AG',
    projectTitle: 'Clinical Data Platform Modernisation',
    industry: 'Healthcare',
    serviceType: 'Data & AI',
    geography: 'Europe',
    deliveryModel: 'Onshore',
    contractValueUSD: 7_900_000,
    durationWeeks: 52,
    technologies: ['IBM Cloud Pak for Data', 'Python', 'Spark', 'Azure', 'CDISC Standards'],
    keywords: ['clinical data', 'pharma', 'CDISC', 'compliance', 'data platform', 'regulatory'],
    outcome: 'LOST',
    winningAttributes: [],
    lossReasons: [
      { category: 'Regulatory Expertise', reason: 'Winning firm had ex-FDA regulatory advisors on the team', mitigationForCurrentProposal: 'Include a named regulatory SME with relevant credentials on the proposed team.' },
      { category: 'References', reason: 'IBM could not provide a CDISC-certified pharma reference within 18 months', mitigationForCurrentProposal: 'Proactively compile pharma reference contacts before submission; offer site visits.' },
    ],
    lessonsLearned: 'Vertical-specific certifications and recent references are table-stakes in regulated industries.',
    confidenceContrib: 0,
    sourceTag: 'Bob IBM Research',
  },
  {
    id: 'eng-017',
    clientName: 'UrbanTransit Authority',
    projectTitle: 'Predictive Maintenance for Rail Fleet',
    industry: 'Public Sector',
    serviceType: 'Managed Services',
    geography: 'North America',
    deliveryModel: 'Onshore',
    contractValueUSD: 4_700_000,
    durationWeeks: 36,
    technologies: ['IBM Maximo', 'Watson IoT', 'Python', 'Edge AI', 'SCADA Integration'],
    keywords: ['predictive maintenance', 'rail', 'public sector', 'IoT', 'maximo', 'SCADA'],
    outcome: 'LOST',
    winningAttributes: [],
    lossReasons: [
      { category: 'Incumbent Advantage', reason: 'Existing vendor held 8-year contract and operational knowledge', mitigationForCurrentProposal: 'Request a formal transition plan section in proposal; highlight data portability guarantees.' },
      { category: 'Governance', reason: 'Public-sector procurement required local small-business sub-contractor', mitigationForCurrentProposal: 'Identify qualified small-business teaming partners before bid submission in public sector RFPs.' },
    ],
    lessonsLearned: 'Public-sector procurement rules around sub-contracting must be understood before structuring the team.',
    confidenceContrib: 0,
  },
  {
    id: 'eng-018',
    clientName: 'MediaStream Corp',
    projectTitle: 'Content Personalisation Engine',
    industry: 'Media & Entertainment',
    serviceType: 'Data & AI',
    geography: 'North America',
    deliveryModel: 'Hybrid',
    contractValueUSD: 3_300_000,
    durationWeeks: 26,
    technologies: ['Watson Studio', 'Elasticsearch', 'Redis', 'Python', 'GraphQL'],
    keywords: ['personalisation', 'recommendation engine', 'media', 'content', 'machine learning', 'streaming'],
    outcome: 'LOST',
    winningAttributes: [],
    lossReasons: [
      { category: 'Speed to Market', reason: 'Winning vendor promised 6-week time-to-production for first model', mitigationForCurrentProposal: 'Package a 4-week fast-start sprint that delivers first model in production before full contract start.' },
      { category: 'Cultural Fit', reason: 'Media client preferred an agency-style agile team over IBM structured delivery', mitigationForCurrentProposal: 'Mirror client agile language; offer embedded squad model rather than traditional PMO waterfall.' },
    ],
    lessonsLearned: 'Media and tech clients value speed and agility signals even before technical evaluation.',
    confidenceContrib: 0,
  },
  {
    id: 'eng-019',
    clientName: 'Commodity Trader Inc',
    projectTitle: 'Risk Analytics Platform',
    industry: 'Financial Services',
    serviceType: 'Data & AI',
    geography: 'North America',
    deliveryModel: 'Hybrid',
    contractValueUSD: 6_200_000,
    durationWeeks: 44,
    technologies: ['IBM OpenPages', 'Watson Studio', 'Python', 'Spark', 'Bloomberg API'],
    keywords: ['risk analytics', 'trading', 'financial services', 'OpenPages', 'real-time', 'compliance'],
    outcome: 'LOST',
    winningAttributes: [],
    lossReasons: [
      { category: 'Technical Fit', reason: 'Client required Bloomberg BLPAPI native connector — IBM had no pre-built integration', mitigationForCurrentProposal: 'Validate all named third-party integration requirements early; secure partners for any gaps.' },
      { category: 'Price', reason: 'OpenPages licensing added 19 % to total cost vs. open-source alternative', mitigationForCurrentProposal: 'Model total licensing cost inclusive of IBM software; show 3-year TCO with support savings.' },
    ],
    lessonsLearned: 'Named technology integrations are often make-or-break — map them to a pre-qualification checklist.',
    confidenceContrib: 0,
    sourceTag: 'Bob IBM Research',
  },
  {
    id: 'eng-020',
    clientName: 'CloudNative Startup',
    projectTitle: 'DevSecOps Transformation',
    industry: 'Technology',
    serviceType: 'Cloud & Platform Services',
    geography: 'North America',
    deliveryModel: 'Offshore',
    contractValueUSD: 1_800_000,
    durationWeeks: 18,
    technologies: ['OpenShift', 'Tekton', 'Aqua Security', 'GitHub Actions', 'Kubernetes'],
    keywords: ['devsecops', 'cloud native', 'ci/cd', 'security scanning', 'pipeline', 'github', 'kubernetes'],
    outcome: 'LOST',
    winningAttributes: [],
    lossReasons: [
      { category: 'Cultural Fit', reason: 'Startup preferred a boutique with open-source-only toolchain', mitigationForCurrentProposal: 'Offer open-source toolchain variant alongside IBM platform options to signal flexibility.' },
      { category: 'Vendor Risk', reason: 'Startup board vetoed IBM due to perceived enterprise lock-in', mitigationForCurrentProposal: 'Lead with exit-strategy portability guarantees and open standards compliance in the executive summary.' },
    ],
    lessonsLearned: 'Technology startups require explicit anti-lock-in assurances before they will shortlist IBM.',
    confidenceContrib: 0,
  },
];
