// ============================================================
// RFP Analyzer Pro — Core Type Definitions (v5)
// ============================================================

export type DocumentStatus = 'uploading' | 'processing' | 'ready' | 'error';

// ============================================================
// Historical Engagement Intelligence
// ============================================================

/** Broad vertical categories used for industry matching weight. */
export type EngagementIndustry =
  | 'Financial Services'
  | 'Healthcare'
  | 'Retail'
  | 'Manufacturing'
  | 'Logistics'
  | 'Energy & Utilities'
  | 'Telecommunications'
  | 'Public Sector'
  | 'Insurance'
  | 'Media & Entertainment'
  | 'Technology'
  | string; // extensible — future industries are allowed

/** IBM service-line bucket used for serviceType matching weight. */
export type EngagementServiceType =
  | 'Cloud & Platform Services'
  | 'Data & AI'
  | 'Security Services'
  | 'Application Modernization'
  | 'Managed Services'
  | 'General Consulting'
  | string;

/** How the engagement was staffed / delivered geographically. */
export type EngagementDeliveryModel = 'Onshore' | 'Offshore' | 'Nearshore' | 'Hybrid' | string;

/** Geography region of the client. */
export type EngagementGeography =
  | 'North America'
  | 'Europe'
  | 'Asia Pacific'
  | 'Latin America'
  | 'Middle East & Africa'
  | string;

/** Win / Loss outcome of the historical engagement. */
export type EngagementOutcome = 'WON' | 'LOST';

/**
 * A single reason why an engagement was lost, paired with a
 * risk-flag mitigation recommendation for the current proposal.
 */
export interface LossReason {
  /** High-level category (e.g. "Price", "Technical Fit", "Vendor Risk"). */
  category: string;
  /** Human-readable description of why the engagement was lost. */
  reason: string;
  /**
   * Actionable recommendation generated by the risk-flag engine
   * to mitigate the same risk in the current proposal.
   */
  mitigationForCurrentProposal: string;
}

/**
 * A historical IBM engagement record used for similarity ranking,
 * win/loss analysis, and Proposal Confidence Score computation.
 *
 * Records tagged with `sourceTag: "Bob IBM Research"` originate from
 * IBM Research / IBM Institute for Business Value and receive a
 * distinct IBM Research badge in the UI.
 */
export interface HistoricalEngagement {
  /** Unique identifier for the engagement record. */
  id: string;
  /** Anonymised or real client name. */
  clientName: string;
  /** Short project title. */
  projectTitle: string;
  /** Client industry vertical. */
  industry: EngagementIndustry;
  /** Primary IBM service type / practice. */
  serviceType: EngagementServiceType;
  /** Client geography region. */
  geography: EngagementGeography;
  /** Staffing / delivery model. */
  deliveryModel: EngagementDeliveryModel;
  /** Total contract value in USD. */
  contractValueUSD: number;
  /** Total engagement duration in calendar weeks. */
  durationWeeks: number;
  /** Technology stack used in this engagement. */
  technologies: string[];
  /** Lower-case keywords for keyword-bonus scoring. */
  keywords: string[];
  /** Final bid outcome. */
  outcome: EngagementOutcome;
  /** Attributes cited as key win factors (only for WON engagements). */
  winningAttributes: string[];
  /** Structured loss reasons (only for LOST engagements). */
  lossReasons: LossReason[];
  /** Narrative lessons learned from the engagement. */
  lessonsLearned: string;
  /**
   * Base confidence contribution of this record when it matches
   * the current proposal (0–1 float, WON only; LOST records use 0).
   */
  confidenceContrib: number;
  /**
   * Optional provenance tag. When equal to `"Bob IBM Research"` the UI
   * renders a distinct IBM Research badge on the engagement card.
   */
  sourceTag?: string;
}

// ── Similarity Engine Output ──────────────────────────────────

/**
 * Weight configuration for the configurable similarity engine.
 * All weights should be positive numbers; they are normalised
 * internally so their relative magnitude is what matters.
 */
export interface SimilarityWeights {
  industry: number;
  serviceType: number;
  contractValue: number;
  technologyStack: number;
  geography: number;
  deliveryModel: number;
  duration: number;
  /** Bonus score applied when a keyword from the engagement matches the current proposal text. */
  keywordBonus: number;
}

/** Default similarity weights — calibrated for balanced matching. */
export const DEFAULT_SIMILARITY_WEIGHTS: SimilarityWeights = {
  industry:       0.22,
  serviceType:    0.20,
  contractValue:  0.12,
  technologyStack: 0.18,
  geography:      0.10,
  deliveryModel:  0.07,
  duration:       0.05,
  keywordBonus:   0.06,
};

/**
 * A single ranked result produced by the similarity engine.
 * Contains the source engagement, its composite similarity score,
 * and a human-readable breakdown per dimension.
 */
export interface SimilarityResult {
  /** The matched historical engagement record. */
  engagement: HistoricalEngagement;
  /** Composite similarity score in the range 0–100. */
  similarityScore: number;
  /** Per-dimension raw scores (0–1) before weighting. */
  dimensionScores: {
    industry: number;
    serviceType: number;
    contractValue: number;
    technologyStack: number;
    geography: number;
    deliveryModel: number;
    duration: number;
    keywordBonus: number;
  };
}

// ── Win / Loss Insight Output ─────────────────────────────────

/** Aggregated win insights derived from top similar WON engagements. */
export interface WinInsights {
  /** Top similar WON engagements ordered by similarity score descending. */
  topWins: SimilarityResult[];
  /** De-duplicated winning attributes frequency ranked. */
  topWinningAttributes: Array<{ attribute: string; frequency: number }>;
  /** Confidence level label derived from win rate and score distribution. */
  confidenceLevel: 'High' | 'Medium' | 'Low';
}

/** Loss reason aggregation across similar LOST engagements. */
export interface LossInsights {
  /** Top similar LOST engagements ordered by similarity score descending. */
  topLosses: SimilarityResult[];
  /** Loss reasons grouped by category across the matched losses. */
  categorisedLossReasons: Array<{
    category: string;
    reasons: string[];
    mitigations: string[];
    frequency: number;
  }>;
}

/**
 * The Overall Proposal Confidence Score (0–100) with its component
 * drivers for the score gauge visualisation and explanation panel.
 */
export interface ProposalConfidenceScore {
  /** Final composite score in the range 0–100. */
  score: number;
  /** Qualitative band label. */
  band: 'Excellent' | 'Good' | 'Fair' | 'Poor';
  /** Individual score drivers summing to the total. */
  drivers: Array<{
    label: string;
    contribution: number; // percentage points contributed to total
    description: string;
  }>;
  /** Number of active risk flags derived from matched loss reasons. */
  activeRiskFlags: number;
  /** Number of similar WON engagements that informed the score. */
  winMatchCount: number;
  /** Completeness score of the current engagement (0–1). */
  completenessScore: number;
}

/** Full output bundle from the HistoricalEngagementService. */
export interface HistoricalInsightsBundle {
  winInsights: WinInsights;
  lossInsights: LossInsights;
  confidenceScore: ProposalConfidenceScore;
  /** ISO timestamp when the analysis was computed. */
  computedAt: string;
}

// ── Input descriptor for the current proposal ────────────────

/**
 * A descriptor of the current RFP / proposal used as the query
 * for similarity matching.  Fields are populated from the existing
 * AnalysisResult, DocumentSummary, and StaffingPlan data.
 */
export interface CurrentEngagementDescriptor {
  industry?: EngagementIndustry;
  serviceType?: EngagementServiceType;
  geography?: EngagementGeography;
  deliveryModel?: EngagementDeliveryModel;
  contractValueUSD?: number;
  durationWeeks?: number;
  technologies?: string[];
  keywords?: string[];
}

export type TabId =
  | 'document-analyzer'
  | 'dashboard'
  | 'scope'
  | 'offerings'
  | 'project-plan'
  | 'staffing'
  | 'testing'
  | 'estimation'
  | 'agentic-impact'
  | 'proposal'
  | 'confidence-insights';

// IBM Band levels
export type IBMBand = '6A' | '6B' | '6G' | '7A' | '7B' | '8' | '9' | '10' | 'Executive' | 'D';

// Service Line for Offerings
export type ServiceLine =
  | 'Cloud & Platform Services'
  | 'Data & AI'
  | 'Security Services'
  | 'Application Modernization'
  | 'Managed Services'
  | 'General Consulting';

export interface RFPDocument {
  id: string;
  name: string;
  size: number;
  type: string;
  status: DocumentStatus;
  uploadedAt: string;
  processedAt?: string;
  rawText?: string;
  /**
   * TASK 3: HTML representation of the document that preserves original visual
   * structure — headings, paragraphs, tables, lists, bold/italic, hyperlinks.
   * Populated for DOCX (via mammoth.convertToHtml). When present, DocumentAnalyzer
   * renders this instead of the plain-text pre-wrap view, giving a faithful
   * reproduction of the source document layout.
   */
  rawHtml?: string;
  summary?: DocumentSummary;
  extractedSections?: ExtractedSections;
  errorMessage?: string;
}

export interface DocumentSummary {
  title: string;
  client: string;
  projectDescription: string;
  estimatedBudget?: string;
  estimatedTimeline?: string;
  keyRequirements: string[];
  technologies: string[];
  deliverables: string[];
  constraints: string[];
  evaluationCriteria: string[];
  wordCount: number;
  pageCount: number;
  confidenceScore: number;
}

export interface ExtractedSections {
  scope: string;
  objectives: string;
  timeline: string;
  budget: string;
  technicalRequirements: string;
  teamRequirements: string;
  evaluationCriteria: string;
  risks: string;
  deliverables: string;
}

// ============================================================
// Scope & Deliverables
// ============================================================
export interface ScopeItem {
  id: string;
  description: string;
  referenceSection: string;
  pageNumber: string;
  category: 'in-scope' | 'out-of-scope' | 'assumption';
  /** Optional: Terms & Conditions text linked from this scope item */
  termsAndConditions?: string;
  /** Optional: Penalties / SLA clause linked from this scope item */
  penalties?: string;
}

export interface DeliverableItem {
  id: string;
  description: string;
  referenceSection: string;
  pageNumber: string;
  phase: string;
  priority: 'high' | 'medium' | 'low';
}

// ============================================================
// Offerings / Technology
// ============================================================
export type OfferingCategory = 'Cloud' | 'AI/ML' | 'Security' | 'Integration' | 'Consulting' | 'Data & Analytics';

export interface IBMOffering {
  id: string;
  name: string;
  category: OfferingCategory;
  serviceLine: ServiceLine;
  description: string;
  relevanceScore: number; // 0-100
  tags: string[];
}

// ============================================================
// Staffing Plan (IBM Band)
// ============================================================
export interface IBMBandInfo {
  band: IBMBand;
  levelDescription: string;
  defaultHourlyRate: number;
}

// ── Monthly utilisation category ─────────────────────────────
// Drives the correct hrs/month cap per the IBM rate-card methodology:
//   Mainline Domestic / Nearshore / Landed INDIA  →  140 hrs/month (all timelines)
//   Offshore CIC Primary INDIA (≤ 12 months)      →  180 hrs/month
//   Offshore CIC Primary INDIA (> 12 months)      →  172.5 hrs/month
export type DeployCategory =
  | 'Mainline Domestic'   // onshore US/EU primary resource
  | 'Nearshore'           // nearshore primary (140 h/mo always)
  | 'Offshore CIC'        // offshore CIC primary – India (180 / 172.5)
  | 'Landed India';       // landed India resource (140 h/mo always)

export interface StaffingRole {
  id: string;
  roleName: string;
  band: IBMBand;
  levelDescription: string;
  numberOfResources: number;
  hoursPerResource: number;
  totalHours: number;
  hourlyRate: number;
  totalCost: number;
  phase?: string;
  weeklyHours?: number;
  /** Optional: overrides the deploy-type in the Staffing table for utilisation calc */
  deployCategory?: DeployCategory;
}

export interface StaffingPlan {
  id: string;
  documentId: string;
  roles: StaffingRole[];
  totalHeadcount: number;
  peakHeadcount: number;
  totalLaborCost: number;
  totalHours: number;
  lastUpdated: string;
}

// ============================================================
// Project Plan
// ============================================================
export interface ProjectPhase {
  id: string;
  name: string;
  description?: string;
  owner?: string;
  milestones?: string[];
  startWeek: number;
  durationWeeks: number;
  endWeek: number;
  responsibleRoles: string[];
  deliverables: string[];
  status: 'not-started' | 'in-progress' | 'completed';
}

export interface ProjectPlan {
  id: string;
  documentId: string;
  projectName: string;
  totalDurationWeeks: number;
  phases: ProjectPhase[];
  lastUpdated: string;
}

// ============================================================
// Testing Strategy
// ============================================================
export interface TestSection {
  id: string;
  type: 'Unit' | 'Integration' | 'UAT' | 'Performance' | 'Security' | 'Regression';
  scope: string;
  entryCriteria: string[];
  exitCriteria: string[];
  tools: string[];
  estimatedHours: number;
  responsibleBand: IBMBand;
  enabled: boolean;
}

export interface TestingStrategy {
  id: string;
  documentId: string;
  sections: TestSection[];
  totalQAHours: number;
  automationCoverage: number;
  lastUpdated: string;
}

// ============================================================
// Estimation + Cost Assumptions
// ============================================================

export interface CostAssumptions {
  rateMultiplier: number;
  contingencyPct: number;
  infrastructurePct: number;
  overheadPct: number;
  travelPct: number;
  licensingFlatUSD: number;
}

export const DEFAULT_COST_ASSUMPTIONS: CostAssumptions = {
  rateMultiplier: 1.0,
  contingencyPct: 10,
  infrastructurePct: 8,
  overheadPct: 12,
  travelPct: 3,
  licensingFlatUSD: 0,
};

export interface EstimationRow {
  id: string;
  activity: string;
  role: string;
  band: IBMBand;
  hours: number;
  ratePerHour: number;
  cost: number;
  phase: string;
}

export interface EstimationSummary {
  id: string;
  documentId: string;
  rows: EstimationRow[];
  totalHours: number;
  totalCost: number;
  adjustedTotalCost: number;
  costBreakdown: CostBreakdown;
  personDays: number;
  personMonths: number;
  phaseSubtotals: Array<{ phase: string; hours: number; cost: number }>;
  lastUpdated: string;
}

export interface CostBreakdown {
  baseLaborCost: number;
  contingencyAmount: number;
  infrastructureAmount: number;
  overheadAmount: number;
  travelAmount: number;
  licensingAmount: number;
  totalAdjustedCost: number;
}

// ============================================================
// Agentic Impact (formerly AI Impact)
// ============================================================
export interface AIPhaseRow {
  id: string;
  phase: string;
  activity: string;
  traditionalHours: number;
  aiAssistedHours: number;
  hoursSaved: number;
  productivityGainPct: number;
}

export interface AIRoleRow {
  id: string;
  role: string;
  band: IBMBand;
  traditionalFTE: number;
  aiAugmentedFTE: number;
  productivityPct: number;
  automationCoveragePct: number;
  reworkReductionPct: number;
  accelerationFactor: number;
  toolUsed: string;
  agentName?: string;
  modelName?: string;
  tokenUsage?: number;
  costPerRun?: number;
}

export interface AIImpact {
  id: string;
  documentId: string;
  phaseRows: AIPhaseRow[];
  roleRows: AIRoleRow[];
  totalTraditionalHours: number;
  totalAIHours: number;
  totalHoursSaved: number;
  overallProductivityGain: number;
  lastUpdated: string;
}

// ── Timeline / Support Events ─────────────────────────────────
export type TimelineEventKind =
  | 'start'
  | 'milestone'
  | 'phase'
  | 'deadline'
  | 'go-live'
  | 'end'
  | 'other';

export interface TimelineEvent {
  id: string;
  label: string;
  /** Raw date string as found in the document (e.g. "01/06/2025") */
  rawDate: string;
  /** Normalised ISO date string yyyy-MM-dd for sorting */
  isoDate: string;
  kind: TimelineEventKind;
  /** Original sentence / snippet the date was extracted from */
  context: string;
}

export type SupportEventKind = 'hypercare' | 'support' | 'warranty' | 'maintenance' | 'sla' | 'other';

export interface SupportEvent {
  id: string;
  label: string;
  rawDate: string;
  isoDate: string;
  kind: SupportEventKind;
  context: string;
  /** Duration string if found (e.g. "3 months", "90 days") */
  duration?: string;
}

// ============================================================
// Global Analysis Result
// ============================================================
export interface AnalysisResult {
  documentId: string;
  scopeItems?: ScopeItem[];
  deliverableItems?: DeliverableItem[];
  offerings?: IBMOffering[];
  projectPlan?: ProjectPlan;
  staffingPlan?: StaffingPlan;
  testingStrategy?: TestingStrategy;
  estimation?: EstimationSummary;
  aiImpact?: AIImpact;
  /** Real dates/milestones extracted from the uploaded document */
  timelineEvents?: TimelineEvent[];
  /** Support / hypercare / warranty dates extracted from the uploaded document */
  supportEvents?: SupportEvent[];
  generatedAt: string;
}

// Popup notification
export interface ChangeNotification {
  id: string;
  sourceModule: string;
  affectedModules: string[];
  message: string;
  pendingUpdate: () => void;
}

export interface DashboardMetric {
  label: string;
  value: string | number;
  unit?: string;
  change?: number;
  trend?: 'up' | 'down' | 'neutral';
  color?: string;
}

