// ============================================================
// Mock Salesforce SOQL Query Endpoint
// Mimics GET /services/data/v59.0/query?q=...
// Returns a realistic set of IBM Opportunity records in the
// exact shape the engagements route expects from ibmsc.
//
// Active when SF_MOCK_MODE=true.
// All records use realistic IBM project names, amounts, and
// technology stacks to exercise the full similarity pipeline.
// ============================================================

import { NextResponse } from 'next/server';

// Shape mirrors what the real Salesforce REST API returns
interface MockOpportunity {
  Id: string;
  Name: string;
  StageName: 'Closed Won' | 'Closed Lost';
  Amount: number;
  CloseDate: string;
  Industry__c: string;
  ServiceType__c: string;
  Geography__c: string;
  DeliveryModel__c: string;
  DurationWeeks__c: number;
  Technologies__c: string;
  Keywords__c: string;
  WinningAttributes__c: string | null;
  LossReasons__c: string | null;
  LessonsLearned__c: string;
  Account: { Name: string };
}

const MOCK_OPPORTUNITIES: MockOpportunity[] = [
  // ── WON ────────────────────────────────────────────────────
  {
    Id: 'sf-001',
    Name: 'Enterprise Cloud Migration — Core Banking',
    StageName: 'Closed Won',
    Amount: 9_500_000,
    CloseDate: '2024-03-15',
    Industry__c: 'Financial Services',
    ServiceType__c: 'Cloud & Platform Services',
    Geography__c: 'North America',
    DeliveryModel__c: 'Hybrid',
    DurationWeeks__c: 56,
    Technologies__c: 'IBM Cloud;OpenShift;Terraform;Ansible;IBM Z',
    Keywords__c: 'cloud migration;banking;mainframe;hybrid cloud;devops;openshift',
    WinningAttributes__c: 'IBM Z hybrid cloud reference architecture;Dedicated migration factory team;Zero-downtime cutover plan accepted by CTO',
    LossReasons__c: null,
    LessonsLearned__c: 'Presenting a dedicated migration factory with named leads won the technical evaluation.',
    Account: { Name: 'MidContinent Bank Corp' },
  },
  {
    Id: 'sf-002',
    Name: 'AI-Driven Risk Scoring Platform',
    StageName: 'Closed Won',
    Amount: 4_200_000,
    CloseDate: '2024-01-22',
    Industry__c: 'Financial Services',
    ServiceType__c: 'Data & AI',
    Geography__c: 'Europe',
    DeliveryModel__c: 'Offshore',
    DurationWeeks__c: 32,
    Technologies__c: 'IBM watsonx.ai;Watson Studio;IBM OpenPages;Python;Spark',
    Keywords__c: 'risk scoring;AI;compliance;watsonx;model governance;banking',
    WinningAttributes__c: 'watsonx.ai EU data residency satisfied GDPR requirement;OpenPages pre-integrated with existing GRC;4-week fast-start POC delivered in sprint 1',
    LossReasons__c: null,
    LessonsLearned__c: 'GDPR-compliant AI platform was the decisive differentiator over US hyperscaler bids.',
    Account: { Name: 'EuroFinance Holdings' },
  },
  {
    Id: 'sf-003',
    Name: 'Zero-Trust Security Transformation',
    StageName: 'Closed Won',
    Amount: 6_100_000,
    CloseDate: '2023-11-10',
    Industry__c: 'Healthcare',
    ServiceType__c: 'Security Services',
    Geography__c: 'North America',
    DeliveryModel__c: 'Onshore',
    DurationWeeks__c: 44,
    Technologies__c: 'IBM Security QRadar;IBM Guardium;Verify;Zero-Trust Architecture;SIEM',
    Keywords__c: 'zero-trust;security;healthcare;HIPAA;compliance;SIEM;identity',
    WinningAttributes__c: 'HIPAA-certified delivery methodology;QRadar + Guardium joint licensing saving 18%;Named CISO advisor on proposal team',
    LossReasons__c: null,
    LessonsLearned__c: 'Including a named CISO-level advisor elevated the proposal above purely technical competition.',
    Account: { Name: 'HealthFirst Network' },
  },
  {
    Id: 'sf-004',
    Name: 'Generative AI Customer Service Platform',
    StageName: 'Closed Won',
    Amount: 3_800_000,
    CloseDate: '2024-05-08',
    Industry__c: 'Retail',
    ServiceType__c: 'Data & AI',
    Geography__c: 'Europe',
    DeliveryModel__c: 'Hybrid',
    DurationWeeks__c: 26,
    Technologies__c: 'IBM watsonx.ai;watsonx Assistant;Llama-3;REST APIs;IBM Cloud',
    Keywords__c: 'generative AI;customer service;LLM;retail;chatbot;watsonx;personalisation',
    WinningAttributes__c: 'Out-of-box retail intent library reduced tuning time by 6 weeks;On-prem watsonx option addressed data sovereignty concern;Live demo with client data in orals',
    LossReasons__c: null,
    LessonsLearned__c: 'Running a live orals demo on the client\'s own data closed the deal.',
    Account: { Name: 'PanEuro Retail Group' },
  },
  {
    Id: 'sf-005',
    Name: 'Kubernetes Platform Engineering Programme',
    StageName: 'Closed Won',
    Amount: 7_300_000,
    CloseDate: '2023-09-29',
    Industry__c: 'Telecommunications',
    ServiceType__c: 'Cloud & Platform Services',
    Geography__c: 'Asia Pacific',
    DeliveryModel__c: 'Offshore',
    DurationWeeks__c: 48,
    Technologies__c: 'OpenShift;Kubernetes;IBM Cloud;Tekton;Istio;Prometheus',
    Keywords__c: 'kubernetes;platform engineering;telco;devops;gitops;observability;openshift',
    WinningAttributes__c: 'GitOps-first delivery cut release cycle by 65%;Dedicated SRE team from day one;Offshore CIC delivered 30% below nearest competitor',
    LossReasons__c: null,
    LessonsLearned__c: 'SRE team availability from week one was the primary technical win factor.',
    Account: { Name: 'AsiaPac Telco Ltd' },
  },
  {
    Id: 'sf-006',
    Name: 'Smart Manufacturing IoT Analytics',
    StageName: 'Closed Won',
    Amount: 5_600_000,
    CloseDate: '2024-02-14',
    Industry__c: 'Manufacturing',
    ServiceType__c: 'Data & AI',
    Geography__c: 'Europe',
    DeliveryModel__c: 'Nearshore',
    DurationWeeks__c: 40,
    Technologies__c: 'IBM Maximo;Watson IoT;Edge Computing;Python;MQTT;Kafka',
    Keywords__c: 'IoT;smart manufacturing;predictive maintenance;edge;maximo;kafka;industry 4.0',
    WinningAttributes__c: 'Maximo pre-built connectors for 12 sensor types;Edge-to-cloud latency under 50ms demonstrated in POC;German-speaking nearshore leads',
    LossReasons__c: null,
    LessonsLearned__c: 'Pre-built sensor connectors halved the integration estimate and won the commercial evaluation.',
    Account: { Name: 'BavarianAuto GmbH' },
  },
  {
    Id: 'sf-007',
    Name: 'Open Banking API Gateway',
    StageName: 'Closed Won',
    Amount: 2_900_000,
    CloseDate: '2023-12-05',
    Industry__c: 'Financial Services',
    ServiceType__c: 'Cloud & Platform Services',
    Geography__c: 'Asia Pacific',
    DeliveryModel__c: 'Offshore',
    DurationWeeks__c: 28,
    Technologies__c: 'IBM API Connect;OpenShift;OAuth 2.0;Kong;Kubernetes;FAPI',
    Keywords__c: 'open banking;API gateway;PSD2;fintech;APAC;oauth;fapi;compliance',
    WinningAttributes__c: 'IBM API Connect pre-certified for MAS TRM;Rate sandbox in sprint 1;Offshore team had APAC banking accelerators',
    LossReasons__c: null,
    LessonsLearned__c: 'Regulatory pre-certification documentation saved 5 weeks of legal review.',
    Account: { Name: 'Pacific Digital Bank' },
  },
  {
    Id: 'sf-008',
    Name: 'Managed Security Operations Centre',
    StageName: 'Closed Won',
    Amount: 11_200_000,
    CloseDate: '2023-08-18',
    Industry__c: 'Energy & Utilities',
    ServiceType__c: 'Managed Services',
    Geography__c: 'North America',
    DeliveryModel__c: 'Hybrid',
    DurationWeeks__c: 104,
    Technologies__c: 'IBM QRadar SIEM;IBM Resilient;Instana;Python;SOAR',
    Keywords__c: 'managed SOC;security;energy;OT security;SIEM;SOAR;24x7;threat detection',
    WinningAttributes__c: '24/7 hybrid SOC with OT/IT convergence expertise;NERC CIP compliance built into runbooks;SLA-backed 15-min MTTR for critical incidents',
    LossReasons__c: null,
    LessonsLearned__c: 'OT security specialisation was not available from any other bidder — unique differentiator.',
    Account: { Name: 'GridPower Energy Corp' },
  },
  {
    Id: 'sf-009',
    Name: 'Public Sector Digital Identity Platform',
    StageName: 'Closed Won',
    Amount: 8_400_000,
    CloseDate: '2024-04-01',
    Industry__c: 'Public Sector',
    ServiceType__c: 'Application Modernization',
    Geography__c: 'North America',
    DeliveryModel__c: 'Onshore',
    DurationWeeks__c: 60,
    Technologies__c: 'IBM Security Verify;OpenID Connect;FIDO2;IBM Carbon Design;React;Node.js',
    Keywords__c: 'digital identity;government;FedRAMP;accessibility;WCAG;citizen services;identity',
    WinningAttributes__c: 'FedRAMP-authorised IBM Cloud;Carbon Design WCAG 2.1 AA out of box;Existing GSA schedule reduced procurement by 3 months',
    LossReasons__c: null,
    LessonsLearned__c: 'Existing government schedule agreements are a hard competitive moat — always lead with them.',
    Account: { Name: 'US Federal Dept of Services' },
  },
  {
    Id: 'sf-010',
    Name: 'Insurance Claims AI Automation',
    StageName: 'Closed Won',
    Amount: 4_700_000,
    CloseDate: '2024-06-20',
    Industry__c: 'Insurance',
    ServiceType__c: 'Data & AI',
    Geography__c: 'Europe',
    DeliveryModel__c: 'Hybrid',
    DurationWeeks__c: 30,
    Technologies__c: 'IBM watsonx.ai;IBM Cloud Pak for Data;Llama-3;Python;REST APIs',
    Keywords__c: 'insurance;claims automation;generative AI;LLM;watsonx;EU AI Act;document processing',
    WinningAttributes__c: 'EU AI Act compliance documentation included;Pre-built claims extraction prompt library;IBM Research hallucination mitigation paper cited',
    LossReasons__c: null,
    LessonsLearned__c: 'EU AI Act compliance readiness was cited by the procurement panel as the top selection factor.',
    Account: { Name: 'EuroShield Insurance' },
  },
  {
    Id: 'sf-011',
    Name: 'AIOps Network Automation Transformation',
    StageName: 'Closed Won',
    Amount: 8_900_000,
    CloseDate: '2023-07-12',
    Industry__c: 'Telecommunications',
    ServiceType__c: 'Managed Services',
    Geography__c: 'North America',
    DeliveryModel__c: 'Offshore',
    DurationWeeks__c: 64,
    Technologies__c: 'IBM AIOps;Instana;OpenShift;Kafka;Python;Ansible',
    Keywords__c: 'AIOps;network automation;observability;telecom;MTTR;managed services;NOC',
    WinningAttributes__c: 'Instana full-stack observability from day one;45% MTTR reduction in pilot;24/7 India CIC NOC at competitive cost',
    LossReasons__c: null,
    LessonsLearned__c: 'MTTR reduction numbers from the pilot environment were the most persuasive asset in orals.',
    Account: { Name: 'NorthAm Telecom Inc' },
  },
  {
    Id: 'sf-012',
    Name: 'SAP S/4HANA Supply Chain Integration',
    StageName: 'Closed Won',
    Amount: 13_500_000,
    CloseDate: '2023-05-30',
    Industry__c: 'Manufacturing',
    ServiceType__c: 'Application Modernization',
    Geography__c: 'Europe',
    DeliveryModel__c: 'Nearshore',
    DurationWeeks__c: 76,
    Technologies__c: 'SAP S/4HANA;IBM Sterling;IBM MQ;Integration Bus;Ansible',
    Keywords__c: 'SAP;ERP migration;manufacturing;supply chain;sterling;integration;nearshore',
    WinningAttributes__c: 'Sterling supply-chain accelerators;Nearshore German-speaking leads;Fixed-price milestone model',
    LossReasons__c: null,
    LessonsLearned__c: 'Language alignment with nearshore team mentioned in 3 of 4 reference calls.',
    Account: { Name: 'CentralEuro Motors AG' },
  },

  // ── LOST ───────────────────────────────────────────────────
  {
    Id: 'sf-013',
    Name: 'E-Commerce Replatform to AWS',
    StageName: 'Closed Lost',
    Amount: 10_500_000,
    CloseDate: '2024-01-30',
    Industry__c: 'Retail',
    ServiceType__c: 'Cloud & Platform Services',
    Geography__c: 'North America',
    DeliveryModel__c: 'Offshore',
    DurationWeeks__c: 60,
    Technologies__c: 'Kubernetes;AWS;React;Microservices;GraphQL',
    Keywords__c: 'e-commerce;replatform;AWS;microservices;retail;graphql',
    WinningAttributes__c: null,
    LossReasons__c: 'Price: IBM day-rate 26% above winning bid;Speed to Market: Client required 8-week MVP but IBM proposed 14 weeks',
    LessonsLearned__c: 'Retail clients prioritise velocity. Lead with an 8-week fast-start MVP scope in all future retail bids.',
    Account: { Name: 'MegaRetail Corp' },
  },
  {
    Id: 'sf-014',
    Name: 'Legacy Policy Admin System Replacement',
    StageName: 'Closed Lost',
    Amount: 17_000_000,
    CloseDate: '2023-10-14',
    Industry__c: 'Insurance',
    ServiceType__c: 'Application Modernization',
    Geography__c: 'Europe',
    DeliveryModel__c: 'Hybrid',
    DurationWeeks__c: 96,
    Technologies__c: 'Java;IBM MQ;Oracle DB;Angular',
    Keywords__c: 'insurance;legacy replacement;policy admin;transformation;core system',
    WinningAttributes__c: null,
    LossReasons__c: 'Vendor Risk: Client cited single-vendor risk;Domain Expertise: Winning vendor had dedicated insurance product accelerator;Price: TCV 20% over budget ceiling',
    LessonsLearned__c: 'Phase-gate structure with early exit options is essential for large transformation deals to stay within client budget cycles.',
    Account: { Name: 'GlobalInsure Group' },
  },
  {
    Id: 'sf-015',
    Name: 'Clinical Data Modernisation',
    StageName: 'Closed Lost',
    Amount: 7_200_000,
    CloseDate: '2023-06-22',
    Industry__c: 'Healthcare',
    ServiceType__c: 'Data & AI',
    Geography__c: 'Europe',
    DeliveryModel__c: 'Onshore',
    DurationWeeks__c: 52,
    Technologies__c: 'IBM Cloud Pak for Data;Python;Spark;Azure;CDISC Standards',
    Keywords__c: 'clinical data;pharma;CDISC;regulatory;data platform;FDA;compliance',
    WinningAttributes__c: null,
    LossReasons__c: 'Regulatory Expertise: Winning firm had ex-FDA regulatory advisors;References: No CDISC-certified pharma reference within 18 months',
    LessonsLearned__c: 'Regulated industries require domain-certified team members and current references — prepare both before submission.',
    Account: { Name: 'Continental Pharma AG' },
  },
  {
    Id: 'sf-016',
    Name: 'Real-Time Logistics Tracking Platform',
    StageName: 'Closed Lost',
    Amount: 2_400_000,
    CloseDate: '2024-03-05',
    Industry__c: 'Logistics',
    ServiceType__c: 'Data & AI',
    Geography__c: 'Asia Pacific',
    DeliveryModel__c: 'Offshore',
    DurationWeeks__c: 20,
    Technologies__c: 'Kafka;Spark Streaming;AWS;React Native;GPS APIs',
    Keywords__c: 'real-time;tracking;logistics;streaming;mobile;kafka;GPS;APAC',
    WinningAttributes__c: null,
    LossReasons__c: 'Technical Fit: Client mandated AWS-native but IBM proposed OpenShift on AWS;Price: 35% day-rate differential vs local APAC boutique',
    LessonsLearned__c: 'Respect client cloud mandates explicitly. When a mandate exists lead with that platform natively.',
    Account: { Name: 'FastShip Logistics' },
  },
  {
    Id: 'sf-017',
    Name: 'Content Personalisation Engine',
    StageName: 'Closed Lost',
    Amount: 3_100_000,
    CloseDate: '2023-11-28',
    Industry__c: 'Media & Entertainment',
    ServiceType__c: 'Data & AI',
    Geography__c: 'North America',
    DeliveryModel__c: 'Hybrid',
    DurationWeeks__c: 26,
    Technologies__c: 'Watson Studio;Elasticsearch;Redis;Python;GraphQL',
    Keywords__c: 'personalisation;recommendation;media;content;machine learning;streaming',
    WinningAttributes__c: null,
    LossReasons__c: 'Speed to Market: Winning vendor promised 6-week time-to-production;Cultural Fit: Media client preferred agency-style agile team',
    LessonsLearned__c: 'Media clients value speed and agility signals. Mirror client agile language and offer an embedded squad model.',
    Account: { Name: 'MediaStream Corp' },
  },
  {
    Id: 'sf-018',
    Name: 'Predictive Maintenance Rail Fleet',
    StageName: 'Closed Lost',
    Amount: 4_400_000,
    CloseDate: '2024-02-28',
    Industry__c: 'Public Sector',
    ServiceType__c: 'Managed Services',
    Geography__c: 'North America',
    DeliveryModel__c: 'Onshore',
    DurationWeeks__c: 36,
    Technologies__c: 'IBM Maximo;Watson IoT;Python;Edge AI;SCADA Integration',
    Keywords__c: 'predictive maintenance;rail;public sector;IoT;maximo;SCADA;government',
    WinningAttributes__c: null,
    LossReasons__c: 'Incumbent Advantage: Existing vendor held 8-year contract and operational knowledge;Governance: Public-sector procurement required local small-business sub-contractor',
    LessonsLearned__c: 'Public-sector teaming requirements must be understood before structuring the proposal team.',
    Account: { Name: 'UrbanTransit Authority' },
  },
  {
    Id: 'sf-019',
    Name: 'Commodity Trading Risk Analytics',
    StageName: 'Closed Lost',
    Amount: 5_800_000,
    CloseDate: '2023-09-15',
    Industry__c: 'Financial Services',
    ServiceType__c: 'Data & AI',
    Geography__c: 'North America',
    DeliveryModel__c: 'Hybrid',
    DurationWeeks__c: 44,
    Technologies__c: 'IBM OpenPages;Watson Studio;Python;Spark;Bloomberg API',
    Keywords__c: 'risk analytics;trading;financial services;OpenPages;real-time;bloomberg;compliance',
    WinningAttributes__c: null,
    LossReasons__c: 'Technical Fit: No pre-built Bloomberg BLPAPI connector;Price: OpenPages licensing added 19% vs open-source alternative',
    LessonsLearned__c: 'Named third-party integrations must be validated against a pre-qualification checklist before bid submission.',
    Account: { Name: 'Commodity Trader Inc' },
  },
  {
    Id: 'sf-020',
    Name: 'DevSecOps Cloud Native Transformation',
    StageName: 'Closed Lost',
    Amount: 1_900_000,
    CloseDate: '2024-05-15',
    Industry__c: 'Technology',
    ServiceType__c: 'Cloud & Platform Services',
    Geography__c: 'North America',
    DeliveryModel__c: 'Offshore',
    DurationWeeks__c: 18,
    Technologies__c: 'OpenShift;Tekton;Aqua Security;GitHub Actions;Kubernetes',
    Keywords__c: 'devsecops;cloud native;ci/cd;security scanning;pipeline;github;kubernetes;startup',
    WinningAttributes__c: null,
    LossReasons__c: 'Cultural Fit: Startup preferred open-source-only boutique;Vendor Risk: Board vetoed IBM due to perceived enterprise lock-in',
    LessonsLearned__c: 'Technology startups require explicit anti-lock-in assurances and open-source toolchain options before shortlisting IBM.',
    Account: { Name: 'CloudNative Startup' },
  },
];

export async function GET(request: Request) {
  // Validate bearer token (any non-empty token accepted in mock mode)
  const auth = request.headers.get('Authorization') ?? '';
  if (!auth.startsWith('Bearer ') || auth.length < 8) {
    return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
  }

  return NextResponse.json({
    totalSize: MOCK_OPPORTUNITIES.length,
    done:      true,
    records:   MOCK_OPPORTUNITIES,
  });
}
